version: '3.8'

volumes:
  pgdata:
  static:
  media:

services:

  postgres:
    image: postgis/postgis
    container_name: postgres
    env_file:
      - docker/env/prod/.env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - docker/env/prod/.env.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    container_name: django
    env_file:
      - docker/env/prod/.env.postgres
      - docker/env/prod/.env.django
    volumes:
      - ./:/app
      - static:/static_storage/static
      - media:/static_storage/media
    depends_on:
      - postgres
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate && 
                    gunicorn core.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4"

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django
